/**
 * ============================================================
 * Surge.AI — Production Backend Architecture
 * ============================================================
 * 
 * This file documents the complete backend architecture for
 * the Surge.AI platform. It includes:
 * 
 * 1. Supabase schema (PostgreSQL)
 * 2. Stripe product configuration
 * 3. Environment variable reference
 * 4. Internal engine configuration (never exposed to users)
 * 
 * IMPORTANT: Never expose supplier names, model names, or
 * technical engine details to end users.
 * ============================================================
 */

// ============================================================
// ENVIRONMENT VARIABLES
// ============================================================

export const ENV_REFERENCE = {
  // Supabase
  NEXT_PUBLIC_SUPABASE_URL: 'https://your-project.supabase.co',
  NEXT_PUBLIC_SUPABASE_ANON_KEY: 'your-anon-key',
  SUPABASE_SERVICE_KEY: 'your-service-role-key',

  // Stripe
  STRIPE_SECRET_KEY: 'sk_live_...',
  STRIPE_WEBHOOK_SECRET: 'whsec_...',
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: 'pk_live_...',

  // Stripe Price IDs (generated by scripts/stripe-setup.js)
  STRIPE_SURGE_COINS_STARTER: 'price_...',
  STRIPE_SURGE_COINS_CREATOR: 'price_...',
  STRIPE_SURGE_COINS_PRO: 'price_...',
  STRIPE_SURGE_COINS_ULTRA: 'price_...',
  STRIPE_SURGE_BUCKS_SMALL: 'price_...',
  STRIPE_SURGE_BUCKS_MEDIUM: 'price_...',
  STRIPE_SURGE_BUCKS_LARGE: 'price_...',

  // App
  APP_URL: 'https://surge.ai',

  // Internal engines (NEVER exposed to users)
  IMAGE_ENGINE_URL: 'http://internal:8000',
  IMAGE_ENGINE_API_KEY: 'internal-key',
  VIDEO_ENGINE_URL: 'https://internal-api.com/v2',
  VIDEO_ENGINE_API_KEY: 'supplier-key',

  // Costs
  IMAGE_COST_COINS: '1',
  VIDEO_COST_BUCKS: '3',
};

// ============================================================
// STRIPE PRODUCT CONFIGURATION
// ============================================================

export const STRIPE_CONFIG = {
  surge_coins: [
    { id: 'starter', name: 'Starter Pack', price_gbp: 300, coins: 30 },
    { id: 'creator', name: 'Creator Pack', price_gbp: 700, coins: 80 },
    { id: 'pro', name: 'Pro Pack', price_gbp: 1500, coins: 200 },
    { id: 'ultra', name: 'Ultra Pack', price_gbp: 3000, coins: 450 },
  ],
  surge_bucks: [
    { id: 'small', name: 'Small', price_gbp: 1000, amount: 100 },
    { id: 'medium', name: 'Medium', price_gbp: 2500, amount: 300 },
    { id: 'large', name: 'Large', price_gbp: 5000, amount: 700 },
  ],
};

// ============================================================
// DAILY STREAK REWARDS
// ============================================================

export const STREAK_ENGINE = {
  rewards: [
    { day: 1, coins: 10 },
    { day: 2, coins: 15 },
    { day: 3, coins: 20 },
    { day: 4, coins: 25 },
    { day: 5, coins: 30 }, // Cap at day 5+
  ],
  max_streak_display: 5,
};

// ============================================================
// API ROUTE MAP
// ============================================================

export const API_ROUTES = {
  'POST /api/rewards/daily': 'Claim daily streak reward',
  'POST /api/purchase/surge-coins': 'Create Stripe checkout for coins',
  'POST /api/purchase/surge-bucks': 'Create Stripe checkout for bucks',
  'POST /api/stripe/webhook': 'Handle Stripe webhook events',
  'GET  /api/billing/status': 'Get current balances',
  'POST /api/tool/sdxl': 'Generate image (internal)',
  'POST /api/render': 'Generate video (internal)',
  'GET  /api/images/recent': 'Get recent images',
  'POST /api/supplier/callback': 'Video completion callback (internal)',
};

// ============================================================
// PUBLIC-FACING COPY (safe to show users)
// ============================================================

export const PUBLIC_COPY = {
  tagline: 'Create stunning AI images and premium videos via our low cost Surge.AI. Powered by a dual-currency creator economy.',
  features: {
    image_studio: 'Premium AI image generation',
    video_engine: 'Premium AI video generation',
    daily_rewards: 'Daily login rewards',
  },
  currencies: {
    surge_coins: 'Used for AI image generation. Earn free via daily streaks or purchase bundles.',
    surge_bucks: 'Used for AI video generation and premium features.',
  },
};
